# Generated by Django 4.2.9 on 2024-02-06 07:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipie", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="directions",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="ingrediants",
            field=models.TextField(blank=True, null=True),
        ),
    ]
