# Generated by Django 4.2.9 on 2024-02-02 07:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("extract", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Food",
        ),
        migrations.DeleteModel(
            name="FoodNutrient",
        ),
    ]
